"use client";

import LogoutButton from "@/components/LogoutButton";
import { useRouter } from "next/navigation"; 
import { useEffect, useState } from "react";

export default function DashboardPageSidebarFirst() {
  const [user, setUser] = useState<any>(null);
  const router = useRouter();
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);

  // ✅ Helper: get accessToken from browser memory (sessionStorage)
  function getAccessToken() {
    return sessionStorage.getItem("accessToken");
  }

  async function fetchUser() {
    try {
      let accessToken = getAccessToken();

      if (!accessToken) {
        console.warn("⚠️ No access token found, redirecting to login...");
        router.push("/login");
        return;
      }

      let res = await fetch("http://localhost:3000/api/auth/me", {
        method: "GET",
        headers: {
          Authorization: `Bearer ${accessToken}`,
        },
      });

      // 🔄 If token expired → try refresh
      if (res.status === 401) {
        console.log("🔄 Access token expired, trying refresh...");

        const refreshRes = await fetch("http://localhost:3000/api/auth/refresh-token", {
          method: "POST",
          credentials: "include", // 🔑 send refresh token cookie
        });

        if (!refreshRes.ok) {
          console.error("❌ RefreshToken failed, redirecting to login...");
          router.push("/login");
          return;
        }

        const refreshData = await refreshRes.json();
        accessToken = refreshData.accessToken;

        // Store new accessToken generated by refreshToken
        sessionStorage.setItem("accessToken", accessToken);

        // Retry /me API with new access token to auth user
        res = await fetch("http://localhost:3000/api/auth/me", {
          method: "GET",
          headers: {
            Authorization: `Bearer ${accessToken}`,
          },
        });
      }

      if (!res.ok) {
        console.error("❌ Failed to fetch /me, redirecting...");
        router.push("/login");
        return;
      }

      const data = await res.json();
      setUser(data.user);
    } catch (err) {
      console.error("❌ Error in fetchUser:", err);
      router.push("/login");
    }
  }

  useEffect(() => {
    fetchUser();
  }, []);

  if (!user) {
    return <p className="text-center mt-10">Loading...</p>;
  }

  return ( 
    <div className="flex h-screen bg-gray-100">
      {/* Sidebar */}
      <aside
        className={`${
          isSidebarOpen ? "w-64" : "w-20"
        } fixed top-0 left-0 h-full bg-indigo-700 text-white transition-all duration-300 flex flex-col z-40`}
      >
        {/* Logo */}
        <div className="h-16 flex items-center justify-center text-xl font-bold border-b border-indigo-600">
          🚀 {isSidebarOpen && "MyApp"}
        </div>

        {/* Nav Links */}
        <nav className="flex-1 p-4 space-y-3 overflow-y-auto">
          <a
            href="#"
            className="block px-3 py-2 rounded-lg hover:bg-indigo-600"
          >
            {isSidebarOpen ? "🏠 Dashboard" : "🏠"}
          </a>
          <a
            href="#"
            className="block px-3 py-2 rounded-lg hover:bg-indigo-600"
          >
            {isSidebarOpen ? "📊 Analytics" : "📊"}
          </a>
          <a
            href="#"
            className="block px-3 py-2 rounded-lg hover:bg-indigo-600"
          >
            {isSidebarOpen ? "📊 Profile" : "📊"}
          </a>
          <a
            href="#"
            className="block px-3 py-2 rounded-lg hover:bg-indigo-600"
          >
            {isSidebarOpen ? "📊 Posts" : "📊"}
          </a>                    
          <a
            href="#"
            className="block px-3 py-2 rounded-lg hover:bg-indigo-600"
          >
            {isSidebarOpen ? "⚙️ Settings" : "⚙️"}
          </a>
        </nav>

        {/* Collapse Button */}
        <button
          onClick={() => setIsSidebarOpen(!isSidebarOpen)}
          className="h-12 border-t border-indigo-600 hover:bg-indigo-600"
        >
          {isSidebarOpen ? "«" : "»"}
        </button>
      </aside>

      {/* Main Area */}
      <div className="flex flex-col flex-1 ml-20 md:ml-64">
        {/* Header */}
        <header className="fixed top-0 left-20 md:left-64 right-0 h-16 bg-white shadow flex justify-between items-center gap-4 px-6 z-10">
          <div className="flex justify-start items-center gap-4">
            {/* 🔹 Hamburger button (mobile only) */}
            <button
              className="md:hidden p-2 rounded hover:bg-gray-200"
              onClick={() => setIsSidebarOpen(!isSidebarOpen)}
            >
              Menu
              {/* <Menu size={24} /> */}
            </button>
            <h1 className="text-lg font-bold text-gray-800">Dashboard - sidebar first</h1>
          </div>
          <div className="flex justify-end items-center gap-4">            
            <span className="text-gray-600 hidden sm:block">{user.email}</span>
            <LogoutButton />
          </div>                        
        </header>

        {/* Content (scrollable only if overflow) */}
        <main className="mt-16 p-6 flex-1 overflow-y-auto">
          <h2 className="text-2xl font-semibold mb-4">
            Welcome, {user.name}! 🎉
          </h2>
          <p className="text-gray-600 mb-6">
            You are logged in as <b>{user.email}</b> (ID: {user.id}).
          </p>

          <h2 className="text-2xl font-semibold mb-6">Dashboard Overview</h2>
          {/* Example Analytics Content Blocks */}
          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
            <div className="bg-white rounded-lg shadow p-6">
              <h3 className="text-lg font-medium mb-2">📈 Analytics</h3>
              <p className="text-gray-600">User traffic, sales, and more.</p>
            </div>

            <div className="bg-white rounded-lg shadow p-6">
              <h3 className="text-lg font-medium mb-2">📝 Recent Activity</h3>
              <p className="text-gray-600">Your recent actions show up here.</p>
            </div>

            <div className="bg-white rounded-lg shadow p-6">
              <h3 className="text-lg font-medium mb-2">⚙️ Quick Settings</h3>
              <p className="text-gray-600">
                Manage preferences and configurations.
              </p>
            </div>
          </div>

          {/* Example long content */}
          <div className="mt-8 space-y-6">
            {Array.from({ length: 20 }).map((_, i) => (
              <div
                key={i}
                className="p-4 bg-white rounded-lg shadow hover:shadow-md transition"
              >
                Content Block #{i + 1}
              </div>
            ))}
          </div>

        </main>
      </div>
    </div>
    // <main className="DashboardPage flex flex-col items-center justify-center min-h-screen gap-4">
    //   <h1 className="text-2xl font-bold">Welcome {user.name}! to your Dashboard 🚀</h1>
    //   <p>You are logged in as : ID: {user.id} - Email: {user.email}</p>
    //   <LogoutButton />
    // </main>

  );
}
