"use client";

import LogoutButton from "@/components/LogoutButton";
import { useRouter } from "next/navigation"; 
import { useEffect, useState } from "react";
import Link from "next/link";

export default function DashboardPageHeaderFirst() {
  const [user, setUser] = useState<any>(null);
  const router = useRouter();  

  // ✅ Helper: get accessToken from browser memory (sessionStorage)
  function getAccessToken() {
    return sessionStorage.getItem("accessToken");
  }

  async function fetchUser() {
    try {
      let accessToken = getAccessToken();

      if (!accessToken) {
        console.warn("⚠️ No access token found, redirecting to login...");
        router.push("/login");
        return;
      }

      let res = await fetch("http://localhost:3000/api/auth/me", {
        method: "GET",
        headers: {
          Authorization: `Bearer ${accessToken}`,
        },
      });

      // 🔄 If token expired → try refresh
      if (res.status === 401) {
        console.log("🔄 Access token expired, trying refresh...");

        const refreshRes = await fetch("http://localhost:3000/api/auth/refresh-token", {
          method: "POST",
          credentials: "include", // 🔑 send refresh token cookie
        });

        if (!refreshRes.ok) {
          console.error("❌ RefreshToken failed, redirecting to login...");
          router.push("/login");
          return;
        }

        const refreshData = await refreshRes.json();
        accessToken = refreshData.accessToken;

        // Store new accessToken generated by refreshToken
        sessionStorage.setItem("accessToken", accessToken);

        // Retry /me API with new access token to auth user
        res = await fetch("http://localhost:3000/api/auth/me", {
          method: "GET",
          headers: {
            Authorization: `Bearer ${accessToken}`,
          },
        });
      }

      if (!res.ok) {
        console.error("❌ Failed to fetch /me, redirecting...");
        router.push("/login");
        return;
      }

      const data = await res.json();
      setUser(data.user);
    } catch (err) {
      console.error("❌ Error in fetchUser:", err);
      router.push("/login");
    }
  }

  useEffect(() => {
    fetchUser();
  }, []);

  if (!user) {
    return <p className="text-center mt-10">Loading...</p>;
  }

  return ( 
    <div className="flex flex-col h-screen bg-gray-100">
      {/* 🔹 Top Header */}
      <header className="fixed top-0 left-0 right-0 h-16 bg-indigo-700 text-white flex items-center justify-between px-6 shadow-md z-50">
        <h1 className="text-xl font-bold tracking-wide">🚀 My Dashboard - header first</h1>
        <div className="flex items-center gap-4">
          <span className="hidden md:inline">Hello, Usman</span>
          <LogoutButton />
        </div>
      </header>

      {/* 🔹 Body Wrapper (Sidebar + Content) */}
      <div className="flex flex-1 pt-16">
        {/* Sidebar */}
        <aside className="fixed top-16 left-0 h-[calc(100vh-4rem)] w-60 bg-white shadow-md border-r hidden md:flex flex-col">
          <nav className="flex flex-col p-4 gap-3 text-gray-700 font-medium">
            <Link
              href="/dashboard"
              className="hover:bg-indigo-100 rounded-md px-3 py-2"
            >
              📊 Overview
            </Link>
            <Link
              href="/dashboard/profile"
              className="hover:bg-indigo-100 rounded-md px-3 py-2"
            >
              👤 Profile
            </Link>
            <Link
              href="/dashboard/settings"
              className="hover:bg-indigo-100 rounded-md px-3 py-2"
            >
              ⚙️ Settings
            </Link>
          </nav>
        </aside>

        {/* Main Content (scrollable only if overflow) */}
        <main className="flex-1 ml-0 md:ml-60 p-6 overflow-y-auto">
          <h2 className="text-2xl font-semibold mb-6">Dashboard Overview</h2>

          {/* Example Analytics Content Blocks */}
          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
            <div className="bg-white rounded-lg shadow p-6">
              <h3 className="text-lg font-medium mb-2">📈 Analytics</h3>
              <p className="text-gray-600">User traffic, sales, and more.</p>
            </div>

            <div className="bg-white rounded-lg shadow p-6">
              <h3 className="text-lg font-medium mb-2">📝 Recent Activity</h3>
              <p className="text-gray-600">Your recent actions show up here.</p>
            </div>

            <div className="bg-white rounded-lg shadow p-6">
              <h3 className="text-lg font-medium mb-2">⚙️ Quick Settings</h3>
              <p className="text-gray-600">
                Manage preferences and configurations.
              </p>
            </div>
          </div>

          {/* Example long content */}
          <div className="mt-8 space-y-6">
            {Array.from({ length: 15 }).map((_, i) => (
              <div
                key={i}
                className="p-4 bg-white rounded-lg shadow hover:shadow-md transition"
              >
                Content Block #{i + 1}
              </div>
            ))}
          </div>
        </main>
      </div>
    </div>
    // <main className="DashboardPage flex flex-col items-center justify-center min-h-screen gap-4">
    //   <h1 className="text-2xl font-bold">Welcome {user.name}! to your Dashboard 🚀</h1>
    //   <p>You are logged in as : ID: {user.id} - Email: {user.email}</p>
    //   <LogoutButton />
    // </main>

  );
}
